parameters:
    app.notifications:
        setup_android_es:
            title: "Configurar dispositivo Android"
            description: >-
                Phasellus rhoncus ante dolor, at semper metus aliquam quis.
                Praesent finibus pharetra libero, ut feugiat mauris dapibus blandit. Donec sit.
            cta: "https://trendos.com/"
